/*******************************************************************************
 * Copyright (c) 2013-2015 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Thierry Monteil (Project co-founder) - Management and initial specification,
 *         conception and documentation.
 *     Mahdi Ben Alaya (Project co-founder) - Management and initial specification,
 *         conception, implementation, test and documentation.
 *     Christophe Chassot - Management and initial specification.
 *     Khalil Drira - Management and initial specification.
 *     Yassine Banouar - Initial specification, conception, implementation, test
 *         and documentation.
 *     Guillaume Garzone - Conception, implementation, test and documentation.
 *     Francois Aissaoui - Conception, implementation, test and documentation.
 ******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.24 at 02:52:11 AM CEST
//


package org.eclipse.core;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;


@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@Entity(name="SCLBASE")
public class SclBase {

	@Id
    protected String uri;
    protected String accessRightID;
    
    @XmlSchemaType(name = "dateTime")
    protected String creationTime;
    
    @XmlSchemaType(name = "dateTime")
    protected String lastModifiedTime;
    
    @XmlSchemaType(name = "anyURI")
    @Transient
    protected String sclsReference;
    
    @XmlSchemaType(name = "anyURI")
    @Transient
    protected String applicationsReference;
    
    @XmlSchemaType(name = "anyURI")
    @Transient
    protected String containersReference;
    
    @XmlSchemaType(name = "anyURI")
    @Transient
    protected String groupsReference;
    
    @XmlSchemaType(name = "anyURI")
    @Transient
    protected String accessRightsReference;
    
    @XmlSchemaType(name = "anyURI")
    @Transient
    protected String subscriptionsReference;
    
    @XmlSchemaType(name = "anyURI")
    @Transient
    protected String discoveryReference;

    public SclBase() {
        super();
    }

    public String getCreationTime() {
        return creationTime;
    }

    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    public String getLastModifiedTime() {
        return lastModifiedTime;
    }

    public void setLastModifiedTime(String value) {
        this.lastModifiedTime = value;
    }

    public void setUri(String value) {
        this.uri = value;
    }
}
